### ISSUE TITLE
`vendor` folder is created inside `PicoAuth` directory in the server

### ISSUE THREAD

**Issue by notakoder** [picoauth/picoauth#7]
A folder called `vendor` is created in the `PicoAuth` folder in the server with the following structure.

```
plugins/PicoAuth/vendor/
plugins/PicoAuth/vendor/symfony/
plugins/PicoAuth/vendor/symfony/http-foundation/
plugins/PicoAuth/vendor/symfony/http-foundation/Tests/
plugins/PicoAuth/vendor/symfony/http-foundation/Tests/File/
plugins/PicoAuth/vendor/symfony/http-foundation/Tests/File/Fixtures/
plugins/PicoAuth/vendor/symfony/http-foundation/Tests/File/Fixtures/-test
```

- Each time I delete these folders and files, they are recreated again.
- They exists only in the server, not in the localhost.
- Only one Pico project has these files and folders. Other Pico projects in the server that uses PicoAuth don't.

Can someone help me understand what these files and folders and why are they created?

**Comment by tumapav** [comment]
`symfony/http-foundation` is one of the dependencies, but assuming you installed the plugin using `composer require` and not by downloading the bundle from the Release page, the package files should be located in `pico/vendor/symfony` instead of `pico/plugins/PicoAuth/vendor/symfony`.

I tried to replicate the issue, but no `PicoAuth/vendor` was created in my environment. Are you running anything specific before the files get created? Like running tests or any composer commands?

**Comment by notakoder** [comment]
I deleted the folder and files using an ftp browser and this time, they aren't re-created. I use to delete `/PicoAuth/vendor` using the `sftp` extension. But I never checked whether it was deleted. Perhaps they never were deleted.

I'll keep checking if those files and folders will be created and if they are, I'll update here. For now I am closing the issue.
Thanks by the way for the quick response.
